CREATE TABLE
  IF NOT EXISTS genres (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL
  );

INSERT INTO
  genres (Name)
VALUES
  ('Pop'),
  ('Rock'),
  ('Jazz'),
  ('Classical'),
  ('Hip Hop'),
  ('Electronic'),
  ('R&B'),
  ('Country'),
  ('Reggae'),
  ('Blues'),
  ('Metal'),
  ('Folk'),
  ('Soul'),
  ('Punk'),
  ('Disco'),
  ('Funk'),
  ('Gospel'),
  ('Latin'),
  ('Indie'),
  ('Opera'),
  ('Ska'),
  ('Grunge'),
  ('House'),
  ('Techno'),
  ('Dubstep'),
  ('Drum and Bass'),
  ('Ambient'),
  ('Trance'),
  ('Hardcore'),
  ('Minimal'),
  ('Electro Swing'),
  ('Chillout'),
  ('Trap'),
  ('Downtempo'),
  ('K-Pop'),
  ('J-Pop'),
  ('Garage'),
  ('Industrial'),
  ('Lo-fi'),
  ('Swing'),
  ('Bluegrass'),
  ('Afrobeat'),
  ('Highlife'),
  ('Soca'),
  ('Calypso'),
  ('Zydeco'),
  ('Bachata'),
  ('Samba'),
  ('Bossa Nova'),
  ('Tango'),
  ('Flamenco'),
  ('Cumbia'),
  ('Vallenato'),
  ('Fado'),
  ('Polka'),
  ('Chanson'),
  ('Shoegaze'),
  ('Psychedelic'),
  ('Alternative Rock'),
  ('Progressive Rock'),
  ('Hard Rock'),
  ('Death Metal'),
  ('Black Metal'),
  ('Thrash Metal'),
  ('Glam Rock'),
  ('Synthpop'),
  ('Eurodance'),
  ('New Wave'),
  ('Chillwave'),
  ('Vaporwave'),
  ('Emo'),
  ('Post-Rock'),
  ('Post-Punk'),
  ('Crunk'),
  ('Bounce'),
  ('Dancehall'),
  ('Ragga'),
  ('Goa Trance'),
  ('Psytrance'),
  ('Acid Jazz'),
  ('New Age'),
  ('Gregorian Chant'),
  ('Baroque'),
  ('Romantic'),
  ('Contemporary Classical'),
  ('Minimalist Music'),
  ('Noise'),
  ('Glitch'),
  ('Game Music'),
  ('Anime Music'),
  ('Dance-Pop'),
  ('Dream Pop'),
  ('Britpop'),
  ('Grime'),
  ('UK Garage'),
  ('Future Bass'),
  ('Hardstyle'),
  ('Makossa'),
  ('Coupe-Decale'),
  ('Qawwali'),
  ('Ghazal'),
  ('Turbo-folk'),
  ('Balkan Pop'),
  ('Alte'),
  ('Amapiano'),
  ('Visual Kei'),
  ('Neoclassical'),
  ('Darkwave'),
  ('Industrial Metal'),
  ('Celtic'),
  ('Gypsy Jazz'),
  ('Bebop'),
  ('Hard Bop'),
  ('Modal Jazz'),
  ('Free Jazz'),
  ('Smooth Jazz'),
  ('Avant-Garde Jazz'),
  ('Brass Band'),
  ('Marching Band'),
  ('Drone Music'),
  ('Skiffle'),
  ('Motown'),
  ('Northern Soul'),
  ('Southern Soul'),
  ('Psybient'),
  ('Dark Ambient'),
  ('Tribal House'),
  ('Acid House'),
  ('Deep House'),
  ('Future House'),
  ('Tech House'),
  ('Progressive House'),
  ('Electro House'),
  ('Big Room House'),
  ('Melodic Techno'),
  ('Hard Techno'),
  ('Detroit Techno'),
  ('Minimal Techno'),
  ('Schlager'),
  ('Volksmusik'),
  ('Enka'),
  ('Kayokyoku'),
  ('Trova'),
  ('Son Cubano'),
  ('Merengue'),
  ('Salsa'),
  ('Rhumba'),
  ('Compas'),
  ('Raï'),
  ('Chaabi'),
  ('Klezmer'),
  ('Folk Metal'),
  ('Symphonic Metal'),
  ('Gothic Metal'),
  ('Doom Metal'),
  ('Sludge Metal'),
  ('Power Metal'),
  ('Speed Metal'),
  ('Folk Punk'),
  ('Celtic Punk'),
  ('Digital Hardcore'),
  ('Jersey Club'),
  ('Footwork'),
  ('Juke'),
  ('Turkish Pop'),
  ('Turkish Folk'),
  ('Arabesque'),
  ('Persian Traditional'),
  ('Dangdut'),
  ('Indo Pop'),
  ('Thai Pop'),
  ('Vietnamese Pop'),
  ('Mandopop'),
  ('Cantopop'),
  ('Taiwanese Pop'),
  ('Hong Kong Pop'),
  ('Singaporean Pop'),
  ('Malaysian Pop'),
  ('Philippine Pop'),
  ('Bollywood'),
  ('Indian Classical'),
  ('Indian Folk'),
  ('Ghazal'),
  ('Sufi Music'),
  ('Bhangra'),
  ('Filmi'),
  ('Kwaito'),
  ('Mbalax'),
  ('Highlife'),
  ('Soukous'),
  ('Afro Pop'),
  ('Maskandi'),
  ('Jit'),
  ('Mbira'),
  ('Sungura'),
  ('Hiplife'),
  ('Afro Trap'),
  ('Axé'),
  ('Forró'),
  ('Frevo'),
  ('Pagode'),
  ('Sertanejo'),
  ('Chimurenga'),
  ('Mugithi'),
  ('Benga'),
  ('Kikuyu Pop'),
  ('Taarab');