CREATE TABLE
  IF NOT EXISTS album_genres (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    AlbumID INT NOT NULL,
    GenreID INT NOT NULL,
    FOREIGN KEY (AlbumID) REFERENCES albums (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (GenreID) REFERENCES genres (ID) ON DELETE CASCADE ON UPDATE CASCADE
  );