CREATE TABLE
  IF NOT EXISTS albums (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ArtistID INT NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Year INT NOT NULL,
    FOREIGN KEY (ArtistID) REFERENCES artists (ID) ON DELETE CASCADE ON UPDATE CASCADE
  );