CREATE TABLE
  IF NOT EXISTS songs (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ArtistID INT NOT NULL,
    AlbumID INT NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Feat VARCHAR(255),
    Year VARCHAR(4),
    FOREIGN KEY (ArtistID) REFERENCES artists (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (AlbumID) REFERENCES albums (ID) ON DELETE CASCADE ON UPDATE CASCADE
  );